export type IdeaStatus = "done" | "partial" | "missing";

export type RoadmapIdea = {
  n: number;
  group: string;
  title: string;
  status: IdeaStatus;
};

export const IDEA_GROUPS = [
  "Posts",
  "Preço e cupom",
  "WhatsApp / anti-ban",
  "Mercado Livre",
  "Painel",
  "TCG / nicho",
  "Conversão e qualidade",
  "Operação / risco",
] as const;

export const IDEAS_100: RoadmapIdea[] = [
  { n: 1, group: "Posts", title: "Template por categoria (TCG curto vs eletrônicos com De/Por).", status: "done" },
  { n: 2, group: "Posts", title: "Linha de loja oficial + “verifique se está selecionada”.", status: "done" },
  { n: 3, group: "Posts", title: "Frete grátis só quando o anúncio confirmar.", status: "done" },
  { n: 4, group: "Posts", title: "Hashtag #anuncio opcional no rodapé.", status: "done" },
  { n: 5, group: "Posts", title: "CTA da comunidade TCG só no grupo TCG.", status: "done" },
  { n: 6, group: "Posts", title: "Variar headlines para não parecer robô.", status: "done" },
  { n: 7, group: "Posts", title: "Alternar “à vista / pix / no cupom”.", status: "done" },
  { n: 8, group: "Posts", title: "QR da comunidade na arte.", status: "done" },
  { n: 9, group: "Posts", title: "Aviso de estoque baixo se o ML sinalizar.", status: "done" },
  { n: 10, group: "Posts", title: "Não repetir o mesmo item no mesmo grupo em 7 dias.", status: "done" },
  { n: 11, group: "Posts", title: "Recusar post se o preço subiu >15% desde a fila.", status: "done" },
  { n: 12, group: "Posts", title: "Recusar se o cupom morreu no último minuto.", status: "done" },
  { n: 13, group: "Posts", title: "Versão “flash” de 4 linhas nos horários de pico.", status: "done" },
  { n: 14, group: "Posts", title: "Marca d’água diferente por comunidade.", status: "done" },
  { n: 15, group: "Posts", title: "Preview lado a lado (imagem + texto) antes de Enviar agora.", status: "done" },
  { n: 16, group: "Preço e cupom", title: "Gráfico de 30 dias no card da oferta.", status: "done" },
  { n: 17, group: "Preço e cupom", title: "Alertar no painel quando deixar de ser o menor valor.", status: "done" },
  { n: 18, group: "Preço e cupom", title: "Revalidar cupom 2 min antes do post.", status: "done" },
  { n: 19, group: "Preço e cupom", title: "Priorizar códigos digitáveis (BRINQUEDOS) no TCG.", status: "done" },
  { n: 20, group: "Preço e cupom", title: "Detectar cupom “seguir loja” vs digitável.", status: "done" },
  { n: 21, group: "Preço e cupom", title: "Mostrar economia real só se o De for o de 30 dias (Lei 14.181).", status: "done" },
  { n: 22, group: "Preço e cupom", title: "Histórico por vendedor, não só por MLB.", status: "done" },
  { n: 23, group: "Preço e cupom", title: "Avisar troca de vendedor no mesmo link.", status: "done" },
  { n: 24, group: "Preço e cupom", title: "Testar qty>1 quando o mínimo do cupom exigir.", status: "done" },
  { n: 25, group: "Preço e cupom", title: "Blacklist de cupons que falham 3 vezes.", status: "done" },
  { n: 26, group: "Preço e cupom", title: "Ranking dos cupons que mais convertem.", status: "done" },
  { n: 27, group: "Preço e cupom", title: "Cruzar catálogo “Novos” do ML com a fila TCG.", status: "done" },
  { n: 28, group: "Preço e cupom", title: "Rebaixar oferta se o Por ficar igual ao De.", status: "done" },
  { n: 29, group: "Preço e cupom", title: "Guardar print do PDP no momento do post (prova).", status: "done" },
  { n: 30, group: "Preço e cupom", title: "Comparar com Keepa/Zoom só como referência interna.", status: "done" },
  { n: 31, group: "WhatsApp / anti-ban", title: "Limite por grupo editável (Eletrônicos 55, TCG 45, Achadinhos 90).", status: "done" },
  { n: 32, group: "WhatsApp / anti-ban", title: "Pausa automática após N erros 403/429.", status: "done" },
  { n: 33, group: "WhatsApp / anti-ban", title: "Jitter extra após 3 posts seguidos.", status: "done" },
  { n: 34, group: "WhatsApp / anti-ban", title: "Silêncio no almoço (12h–13h30) opcional.", status: "done" },
  { n: 35, group: "WhatsApp / anti-ban", title: "Domingo ainda mais baixo que sábado.", status: "done" },
  { n: 36, group: "WhatsApp / anti-ban", title: "Rodízio: nunca 2 TCG seguidos se Eletrônicos estiver parado.", status: "done" },
  { n: 37, group: "WhatsApp / anti-ban", title: "Aquecer número novo 7 dias só com 10 posts.", status: "done" },
  { n: 38, group: "WhatsApp / anti-ban", title: "Detectar “mensagem não entregue” e pausar.", status: "done" },
  { n: 39, group: "WhatsApp / anti-ban", title: "Não enviar mídia + texto longo no mesmo segundo.", status: "done" },
  { n: 40, group: "WhatsApp / anti-ban", title: "Backup de sessão Baileys diário.", status: "done" },
  { n: 41, group: "WhatsApp / anti-ban", title: "Dois números: um TCG, um geral.", status: "done" },
  { n: 42, group: "WhatsApp / anti-ban", title: "Horário de “achadinho da madrugada” desligado por padrão.", status: "done" },
  { n: 43, group: "WhatsApp / anti-ban", title: "Relatório diário: enviados / bloqueados / motivo.", status: "done" },
  { n: 44, group: "WhatsApp / anti-ban", title: "Modo “só Enviar agora” em feriados.", status: "done" },
  { n: 45, group: "WhatsApp / anti-ban", title: "Delay maior se o último post teve link + imagem.", status: "done" },
  { n: 46, group: "Mercado Livre", title: "Encher Games/Casa como o TCG (lojas oficiais).", status: "done" },
  { n: 47, group: "Mercado Livre", title: "Scrap de mais páginas da loja Pokémon.", status: "done" },
  { n: 48, group: "Mercado Livre", title: "Filtro “só loja oficial” nas listas.", status: "done" },
  { n: 49, group: "Mercado Livre", title: "Podar anúncios pausados 2x/dia.", status: "done" },
  { n: 50, group: "Mercado Livre", title: "Não misturar createLink com add-to-list.", status: "done" },
  { n: 51, group: "Mercado Livre", title: "Alerta se Cookie/CSRF expirar.", status: "done" },
  { n: 52, group: "Mercado Livre", title: "Renovar sessão com um createLink de teste.", status: "done" },
  { n: 53, group: "Mercado Livre", title: "Mapear lista ↔ grupo WhatsApp 1:1.", status: "done" },
  { n: 54, group: "Mercado Livre", title: "Meta de N itens por lista (TCG ≥ 40).", status: "done" },
  { n: 55, group: "Mercado Livre", title: "Ordenar lista ML por desconto, não por ordem de insert.", status: "done" },
  { n: 56, group: "Mercado Livre", title: "Importar ofertas do Hub “Ganhos extras” por nicho.", status: "done" },
  { n: 57, group: "Mercado Livre", title: "Blacklist de vendedores genéricos no TCG.", status: "done" },
  { n: 58, group: "Mercado Livre", title: "Preferir anúncios com Full/flex.", status: "done" },
  { n: 59, group: "Mercado Livre", title: "Recusar item sem meli.la.", status: "done" },
  { n: 60, group: "Mercado Livre", title: "Logar cada add/remove na lista.", status: "done" },
  { n: 61, group: "Painel", title: "Filtro salvo (ex.: “TCG queued com cupom”).", status: "done" },
  { n: 62, group: "Painel", title: "Ordenar ofertas por comissão / desconto / data.", status: "done" },
  { n: 63, group: "Painel", title: "Card kanban: fila → hold cupom → postado.", status: "done" },
  { n: 64, group: "Painel", title: "Busca também por MLB e meli.la.", status: "done" },
  { n: 65, group: "Painel", title: "Ações em massa: testar cupom nos selecionados.", status: "done" },
  { n: 66, group: "Painel", title: "Dark/contrast um pouco maior nas tabelas.", status: "done" },
  { n: 67, group: "Painel", title: "Atalho teclado / para busca.", status: "done" },
  { n: 68, group: "Painel", title: "Badge “menor 30 dias” na fila.", status: "done" },
  { n: 69, group: "Painel", title: "Contador ao vivo da lista TCG.", status: "done" },
  { n: 70, group: "Painel", title: "Página de “o que vai sair nas próximas 2h”.", status: "done" },
  { n: 71, group: "Painel", title: "Log anti-ban com filtro por tipo.", status: "done" },
  { n: 72, group: "Painel", title: "Export CSV da fila.", status: "done" },
  { n: 73, group: "Painel", title: "Desfazer “resetar envios”.", status: "done" },
  { n: 74, group: "Painel", title: "Confirmar exclusão com nome do produto.", status: "done" },
  { n: 75, group: "Painel", title: "Skeleton loading nas listas grandes.", status: "done" },
  { n: 76, group: "TCG / nicho", title: "Keywords One Piece / Lorcana / Disney.", status: "done" },
  { n: 77, group: "TCG / nicho", title: "Lojas Copag, Pokémon Center, Asmodee sempre ativas.", status: "done" },
  { n: 78, group: "TCG / nicho", title: "Postar idioma (PT-BR vs EN) no título.", status: "done" },
  { n: 79, group: "TCG / nicho", title: "Separar booster vs ETB vs Mega Box.", status: "done" },
  { n: 80, group: "TCG / nicho", title: "Alerta de pré-venda (data de lançamento).", status: "done" },
  { n: 81, group: "TCG / nicho", title: "Não misturar TCG em Games.", status: "done" },
  { n: 82, group: "TCG / nicho", title: "Cupom BRINQUEDOS como padrão do nicho.", status: "done" },
  { n: 83, group: "TCG / nicho", title: "Volume alvo: ≥40 itens na lista TCG.", status: "done" },
  { n: 84, group: "TCG / nicho", title: "Evitar reprints caros sem desconto.", status: "done" },
  { n: 85, group: "TCG / nicho", title: "Comunidade exclusiva TCG no rodapé só desse grupo.", status: "done" },
  { n: 86, group: "Conversão e qualidade", title: "UTM no meli.la por grupo.", status: "done" },
  { n: 87, group: "Conversão e qualidade", title: "Top 10 posts da semana (cliques se o Hub mostrar).", status: "done" },
  { n: 88, group: "Conversão e qualidade", title: "Não postar produto sem foto.", status: "done" },
  { n: 89, group: "Conversão e qualidade", title: "Recortar imagem 1:1 para o WhatsApp.", status: "done" },
  { n: 90, group: "Conversão e qualidade", title: "Legenda alternativa se a imagem falhar.", status: "done" },
  { n: 91, group: "Conversão e qualidade", title: "Score de “parece achadinho” (desconto + cupom + 30 dias).", status: "done" },
  { n: 92, group: "Conversão e qualidade", title: "Fila priorizada por score, não só FIFO.", status: "done" },
  { n: 93, group: "Conversão e qualidade", title: "A/B de duas headlines por categoria.", status: "done" },
  { n: 94, group: "Conversão e qualidade", title: "Bloquear título genérico (“Produto MLB…”).", status: "done" },
  { n: 95, group: "Conversão e qualidade", title: "Reescrever título curto (máx. 90 caracteres).", status: "done" },
  { n: 96, group: "Operação / risco", title: "Backup SQLite automático.", status: "done" },
  { n: 97, group: "Operação / risco", title: "Healthcheck externo (painel fora do ar).", status: "done" },
  { n: 98, group: "Operação / risco", title: "Runbook: Cookie expirou / WA desconectou / lista vazia.", status: "done" },
  { n: 99, group: "Operação / risco", title: "Modo manutenção: zera envios, mantém Sync.", status: "done" },
  { n: 100, group: "Operação / risco", title: "Auditoria mensal: volume vs ban risk vs concorrente.", status: "done" },
];

export function roadmapSummary() {
  const ideas = IDEAS_100;
  const count = (s: IdeaStatus) => ideas.filter((i) => i.status === s).length;
  return {
    total: ideas.length,
    done: count("done"),
    partial: count("partial"),
    missing: count("missing"),
    groups: IDEA_GROUPS,
    ideas,
  };
}
